#!/bin/bash

docker rm -f hpg

docker run --name hpg --network host -e POSTGRES_USER=hubris -e POSTGRES_PASSWORD=hubris -e POSTGRES_DB=hubris -d --rm postgres

sleep 5

migrate -source file://$PWD/internal/database/migrations -database postgres://hubris:hubris@::1/hubris\?sslmode=disable up

sqlboiler -c sqlboiler.toml psql