BEGIN;

CREATE TABLE guilds (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    guild_id text NOT NULL UNIQUE,

    do_mafia bool NOT NULL DEFAULT 'false',
    do_jarvis bool NOT NULL DEFAULT 'false',

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE pronouns (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_id text NOT NULL UNIQUE,
    guild_id text NOT NULL,
    pronoun text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(pronoun, guild_id)
);

COMMIT;